"""
Master asset registry for Fintelligent AI.
All assets are fetched via yfinance — tickers must be valid Yahoo Finance symbols.
"""

from typing import TypedDict, Literal

AssetCategory = Literal["crypto", "stocks", "commodities", "forex", "indices"]


class Asset(TypedDict):
    ticker: str
    label: str
    category: AssetCategory


ASSETS: list[Asset] = [
    # ── Crypto ──────────────────────────────────────────────────────────────
    {"ticker": "BTC-USD",  "label": "Bitcoin",          "category": "crypto"},
    {"ticker": "ETH-USD",  "label": "Ethereum",         "category": "crypto"},
    {"ticker": "SOL-USD",  "label": "Solana",           "category": "crypto"},
    {"ticker": "BNB-USD",  "label": "BNB",              "category": "crypto"},
    {"ticker": "XRP-USD",  "label": "XRP",              "category": "crypto"},
    {"ticker": "ADA-USD",  "label": "Cardano",          "category": "crypto"},
    {"ticker": "DOGE-USD", "label": "Dogecoin",         "category": "crypto"},
    {"ticker": "AVAX-USD", "label": "Avalanche",        "category": "crypto"},
    {"ticker": "LINK-USD", "label": "Chainlink",        "category": "crypto"},
    {"ticker": "DOT-USD",  "label": "Polkadot",         "category": "crypto"},

    # ── US Stocks ────────────────────────────────────────────────────────────
    {"ticker": "AAPL",  "label": "Apple",                      "category": "stocks"},
    {"ticker": "MSFT",  "label": "Microsoft",                  "category": "stocks"},
    {"ticker": "NVDA",  "label": "NVIDIA",                     "category": "stocks"},
    {"ticker": "GOOGL", "label": "Alphabet (Google)",          "category": "stocks"},
    {"ticker": "AMZN",  "label": "Amazon",                     "category": "stocks"},
    {"ticker": "META",  "label": "Meta Platforms",             "category": "stocks"},
    {"ticker": "TSLA",  "label": "Tesla",                      "category": "stocks"},
    {"ticker": "AVGO",  "label": "Broadcom",                   "category": "stocks"},
    {"ticker": "BRK-B", "label": "Berkshire Hathaway B",       "category": "stocks"},
    {"ticker": "LLY",   "label": "Eli Lilly",                  "category": "stocks"},
    {"ticker": "JPM",   "label": "JPMorgan Chase",             "category": "stocks"},
    {"ticker": "V",     "label": "Visa",                       "category": "stocks"},
    {"ticker": "UNH",   "label": "UnitedHealth Group",         "category": "stocks"},
    {"ticker": "XOM",   "label": "ExxonMobil",                 "category": "stocks"},
    {"ticker": "MA",    "label": "Mastercard",                 "category": "stocks"},
    {"ticker": "JNJ",   "label": "Johnson & Johnson",          "category": "stocks"},
    {"ticker": "PG",    "label": "Procter & Gamble",           "category": "stocks"},
    {"ticker": "HD",    "label": "Home Depot",                 "category": "stocks"},
    {"ticker": "COST",  "label": "Costco",                     "category": "stocks"},
    {"ticker": "MRK",   "label": "Merck",                      "category": "stocks"},
    {"ticker": "ABBV",  "label": "AbbVie",                     "category": "stocks"},
    {"ticker": "CRM",   "label": "Salesforce",                 "category": "stocks"},
    {"ticker": "BAC",   "label": "Bank of America",            "category": "stocks"},
    {"ticker": "NFLX",  "label": "Netflix",                    "category": "stocks"},
    {"ticker": "AMD",   "label": "Advanced Micro Devices",     "category": "stocks"},
    {"ticker": "KO",    "label": "Coca-Cola",                  "category": "stocks"},
    {"ticker": "WMT",   "label": "Walmart",                    "category": "stocks"},
    {"ticker": "PEP",   "label": "PepsiCo",                    "category": "stocks"},
    {"ticker": "TMO",   "label": "Thermo Fisher Scientific",   "category": "stocks"},
    {"ticker": "ORCL",  "label": "Oracle",                     "category": "stocks"},
    {"ticker": "MCD",   "label": "McDonald's",                 "category": "stocks"},
    {"ticker": "ACN",   "label": "Accenture",                  "category": "stocks"},
    {"ticker": "CSCO",  "label": "Cisco Systems",              "category": "stocks"},
    {"ticker": "ABT",   "label": "Abbott Laboratories",        "category": "stocks"},
    {"ticker": "GE",    "label": "GE Aerospace",               "category": "stocks"},
    {"ticker": "DHR",   "label": "Danaher",                    "category": "stocks"},
    {"ticker": "IBM",   "label": "IBM",                        "category": "stocks"},
    {"ticker": "TXN",   "label": "Texas Instruments",          "category": "stocks"},
    {"ticker": "QCOM",  "label": "Qualcomm",                   "category": "stocks"},
    {"ticker": "INTU",  "label": "Intuit",                     "category": "stocks"},
    {"ticker": "RTX",   "label": "RTX Corporation",            "category": "stocks"},
    {"ticker": "CAT",   "label": "Caterpillar",                "category": "stocks"},
    {"ticker": "NOW",   "label": "ServiceNow",                 "category": "stocks"},
    {"ticker": "SPGI",  "label": "S&P Global",                 "category": "stocks"},
    {"ticker": "GS",    "label": "Goldman Sachs",              "category": "stocks"},
    {"ticker": "ISRG",  "label": "Intuitive Surgical",         "category": "stocks"},
    {"ticker": "BKNG",  "label": "Booking Holdings",           "category": "stocks"},
    {"ticker": "AMGN",  "label": "Amgen",                      "category": "stocks"},
    {"ticker": "MS",    "label": "Morgan Stanley",             "category": "stocks"},
    {"ticker": "LOW",   "label": "Lowe's Companies",           "category": "stocks"},
    {"ticker": "BLK",   "label": "BlackRock",                  "category": "stocks"},
    {"ticker": "AXP",   "label": "American Express",           "category": "stocks"},
    {"ticker": "UBER",  "label": "Uber Technologies",          "category": "stocks"},
    {"ticker": "PLD",   "label": "Prologis",                   "category": "stocks"},
    {"ticker": "VRTX",  "label": "Vertex Pharmaceuticals",     "category": "stocks"},
    {"ticker": "GILD",  "label": "Gilead Sciences",            "category": "stocks"},
    {"ticker": "DE",    "label": "Deere & Company",            "category": "stocks"},
    {"ticker": "PANW",  "label": "Palo Alto Networks",         "category": "stocks"},
    {"ticker": "ADI",   "label": "Analog Devices",             "category": "stocks"},
    {"ticker": "AMAT",  "label": "Applied Materials",          "category": "stocks"},
    {"ticker": "MU",    "label": "Micron Technology",          "category": "stocks"},
    {"ticker": "LRCX",  "label": "Lam Research",               "category": "stocks"},
    {"ticker": "KLAC",  "label": "KLA Corporation",            "category": "stocks"},
    {"ticker": "SNPS",  "label": "Synopsys",                   "category": "stocks"},
    {"ticker": "CDNS",  "label": "Cadence Design Systems",     "category": "stocks"},
    {"ticker": "WFC",   "label": "Wells Fargo",                "category": "stocks"},
    {"ticker": "C",     "label": "Citigroup",                  "category": "stocks"},
    {"ticker": "USB",   "label": "U.S. Bancorp",               "category": "stocks"},
    {"ticker": "PNC",   "label": "PNC Financial Services",     "category": "stocks"},
    {"ticker": "SCHW",  "label": "Charles Schwab",             "category": "stocks"},
    {"ticker": "CME",   "label": "CME Group",                  "category": "stocks"},
    {"ticker": "ICE",   "label": "Intercontinental Exchange",  "category": "stocks"},
    {"ticker": "TRV",   "label": "Travelers Companies",        "category": "stocks"},
    {"ticker": "AON",   "label": "Aon",                        "category": "stocks"},
    {"ticker": "SYK",   "label": "Stryker",                    "category": "stocks"},
    {"ticker": "BSX",   "label": "Boston Scientific",          "category": "stocks"},
    {"ticker": "MDT",   "label": "Medtronic",                  "category": "stocks"},
    {"ticker": "ELV",   "label": "Elevance Health",            "category": "stocks"},
    {"ticker": "CI",    "label": "Cigna",                      "category": "stocks"},
    {"ticker": "CVS",   "label": "CVS Health",                 "category": "stocks"},
    {"ticker": "HUM",   "label": "Humana",                     "category": "stocks"},
    {"ticker": "LMT",   "label": "Lockheed Martin",            "category": "stocks"},
    {"ticker": "NOC",   "label": "Northrop Grumman",           "category": "stocks"},
    {"ticker": "BA",    "label": "Boeing",                     "category": "stocks"},
    {"ticker": "GD",    "label": "General Dynamics",           "category": "stocks"},
    {"ticker": "HON",   "label": "Honeywell",                  "category": "stocks"},
    {"ticker": "MMM",   "label": "3M",                         "category": "stocks"},
    {"ticker": "EMR",   "label": "Emerson Electric",           "category": "stocks"},
    {"ticker": "ETN",   "label": "Eaton",                      "category": "stocks"},
    {"ticker": "ITW",   "label": "Illinois Tool Works",        "category": "stocks"},
    {"ticker": "PH",    "label": "Parker-Hannifin",            "category": "stocks"},
    {"ticker": "UPS",   "label": "United Parcel Service",      "category": "stocks"},
    {"ticker": "FDX",   "label": "FedEx",                      "category": "stocks"},
    {"ticker": "NSC",   "label": "Norfolk Southern",           "category": "stocks"},
    {"ticker": "UNP",   "label": "Union Pacific",              "category": "stocks"},
    {"ticker": "NEE",   "label": "NextEra Energy",             "category": "stocks"},
    {"ticker": "DUK",   "label": "Duke Energy",                "category": "stocks"},
    {"ticker": "SO",    "label": "Southern Company",           "category": "stocks"},
    {"ticker": "SRE",   "label": "Sempra",                     "category": "stocks"},
    {"ticker": "D",     "label": "Dominion Energy",            "category": "stocks"},
    {"ticker": "CVX",   "label": "Chevron",                    "category": "stocks"},
    {"ticker": "COP",   "label": "ConocoPhillips",             "category": "stocks"},
    {"ticker": "SLB",   "label": "SLB (Schlumberger)",         "category": "stocks"},
    {"ticker": "EOG",   "label": "EOG Resources",              "category": "stocks"},
    {"ticker": "DVN",   "label": "Devon Energy",               "category": "stocks"},
    {"ticker": "OXY",   "label": "Occidental Petroleum",       "category": "stocks"},
    {"ticker": "MPC",   "label": "Marathon Petroleum",         "category": "stocks"},
    {"ticker": "VLO",   "label": "Valero Energy",              "category": "stocks"},
    {"ticker": "PSX",   "label": "Phillips 66",                "category": "stocks"},
    {"ticker": "REGN",  "label": "Regeneron Pharmaceuticals",  "category": "stocks"},
    {"ticker": "BIIB",  "label": "Biogen",                     "category": "stocks"},
    {"ticker": "ILMN",  "label": "Illumina",                   "category": "stocks"},
    {"ticker": "ZTS",   "label": "Zoetis",                     "category": "stocks"},
    {"ticker": "IDXX",  "label": "IDEXX Laboratories",         "category": "stocks"},
    {"ticker": "DIS",   "label": "Walt Disney",                "category": "stocks"},
    {"ticker": "CMCSA", "label": "Comcast",                    "category": "stocks"},
    {"ticker": "CHTR",  "label": "Charter Communications",     "category": "stocks"},
    {"ticker": "T",     "label": "AT&T",                       "category": "stocks"},
    {"ticker": "VZ",    "label": "Verizon",                    "category": "stocks"},
    {"ticker": "TMUS",  "label": "T-Mobile US",                "category": "stocks"},
    {"ticker": "SHOP",  "label": "Shopify",                    "category": "stocks"},
    {"ticker": "SNOW",  "label": "Snowflake",                  "category": "stocks"},
    {"ticker": "PLTR",  "label": "Palantir Technologies",      "category": "stocks"},
    {"ticker": "COIN",  "label": "Coinbase Global",            "category": "stocks"},
    {"ticker": "RBLX",  "label": "Roblox",                     "category": "stocks"},
    {"ticker": "SPOT",  "label": "Spotify Technology",         "category": "stocks"},
    {"ticker": "HOOD",  "label": "Robinhood Markets",          "category": "stocks"},
    {"ticker": "APP",   "label": "AppLovin",                   "category": "stocks"},
    {"ticker": "ARM",   "label": "Arm Holdings",               "category": "stocks"},
    {"ticker": "SMCI",  "label": "Super Micro Computer",       "category": "stocks"},
    {"ticker": "DELL",  "label": "Dell Technologies",          "category": "stocks"},
    {"ticker": "HPQ",   "label": "HP Inc.",                    "category": "stocks"},
    {"ticker": "INTC",  "label": "Intel",                      "category": "stocks"},

    # ── Commodities ──────────────────────────────────────────────────────────
    {"ticker": "GC=F",     "label": "Gold (Spot)",        "category": "commodities"},
    {"ticker": "SI=F",     "label": "Silver (Spot)",      "category": "commodities"},
    {"ticker": "PL=F",     "label": "Platinum",           "category": "commodities"},
    {"ticker": "PA=F",     "label": "Palladium",          "category": "commodities"},
    {"ticker": "CL=F",     "label": "Crude Oil (WTI)",    "category": "commodities"},
    {"ticker": "BZ=F",     "label": "Brent Crude Oil",    "category": "commodities"},
    {"ticker": "NG=F",     "label": "Natural Gas",        "category": "commodities"},
    {"ticker": "HG=F",     "label": "Copper",             "category": "commodities"},
    {"ticker": "ZW=F",     "label": "Wheat",              "category": "commodities"},
    {"ticker": "ZC=F",     "label": "Corn",               "category": "commodities"},
    {"ticker": "ZS=F",     "label": "Soybeans",           "category": "commodities"},
    {"ticker": "CC=F",     "label": "Cocoa",              "category": "commodities"},
    {"ticker": "KC=F",     "label": "Coffee",             "category": "commodities"},
    {"ticker": "SB=F",     "label": "Sugar",              "category": "commodities"},

    # ── Forex ────────────────────────────────────────────────────────────────
    {"ticker": "EURUSD=X", "label": "EUR/USD",  "category": "forex"},
    {"ticker": "GBPUSD=X", "label": "GBP/USD",  "category": "forex"},
    {"ticker": "USDJPY=X", "label": "USD/JPY",  "category": "forex"},
    {"ticker": "AUDUSD=X", "label": "AUD/USD",  "category": "forex"},
    {"ticker": "USDCAD=X", "label": "USD/CAD",  "category": "forex"},
    {"ticker": "NZDUSD=X", "label": "NZD/USD",  "category": "forex"},
    {"ticker": "USDCHF=X", "label": "USD/CHF",  "category": "forex"},
    {"ticker": "EURGBP=X", "label": "EUR/GBP",  "category": "forex"},
    {"ticker": "EURJPY=X", "label": "EUR/JPY",  "category": "forex"},
    {"ticker": "GBPJPY=X", "label": "GBP/JPY",  "category": "forex"},
    {"ticker": "USDMXN=X", "label": "USD/MXN",  "category": "forex"},
    {"ticker": "USDZAR=X", "label": "USD/ZAR",  "category": "forex"},
    {"ticker": "USDSGD=X", "label": "USD/SGD",  "category": "forex"},
    {"ticker": "USDHKD=X", "label": "USD/HKD",  "category": "forex"},
    {"ticker": "USDCNH=X", "label": "USD/CNH",  "category": "forex"},
    {"ticker": "USDINR=X", "label": "USD/INR",  "category": "forex"},

    # ── Indices ──────────────────────────────────────────────────────────────
    {"ticker": "^GSPC",  "label": "S&P 500",          "category": "indices"},
    {"ticker": "^NDX",   "label": "Nasdaq 100",        "category": "indices"},
    {"ticker": "^DJI",   "label": "Dow Jones",         "category": "indices"},
    {"ticker": "^RUT",   "label": "Russell 2000",      "category": "indices"},
    {"ticker": "^VIX",   "label": "VIX",               "category": "indices"},
    {"ticker": "^FTSE",  "label": "FTSE 100",          "category": "indices"},
    {"ticker": "^GDAXI", "label": "DAX 40",            "category": "indices"},
    {"ticker": "^FCHI",  "label": "CAC 40",            "category": "indices"},
    {"ticker": "^N225",  "label": "Nikkei 225",        "category": "indices"},
    {"ticker": "^HSI",   "label": "Hang Seng",         "category": "indices"},
    {"ticker": "^KS11",  "label": "KOSPI",              "category": "indices"},
    {"ticker": "^BSESN", "label": "BSE Sensex",        "category": "indices"},
    {"ticker": "^AXJO",  "label": "ASX 200",           "category": "indices"},
    {"ticker": "^STOXX50E","label": "Euro Stoxx 50",   "category": "indices"},
]

TICKER_MAP: dict[str, Asset] = {a["ticker"]: a for a in ASSETS}


def search_assets(query: str, category: AssetCategory | None = None) -> list[Asset]:
    """Search assets by ticker or label, optionally filtered by category."""
    q = query.strip().upper()
    results = []
    for asset in ASSETS:
        if category and asset["category"] != category:
            continue
        if q in asset["ticker"].upper() or q in asset["label"].upper():
            results.append(asset)
    return results[:20]
